### ISSUE TITLE
CocoaDialog.app needs updating

### ISSUE THREAD

**Issue by whaynes** [mattneub/RubyFrontier#6]
I'm still on Mojave and today when I selected  RubyFrontier > Locate User.rb File  I got the 32 bit warning that:

> CocoaDialog.app” is not optimized for your Mac and needs to be updated.

I hope that you're still maintaining RubyFrontier as it's a critical part of my workflow.

Thanks
William Haynes

**Comment by whaynes** [comment]
This is not a problem with rubyFrontier apparently,

https://github.com/textmate/bundle-support.tmbundle/issues/31

**Comment by mattneub** [comment]
I’ve removed RubyFrontier’s dependency on CocoaDialog, but meanwhile a 64 bit version is also on the way.
